[package]
license = "Apache-2.0"
name = "fuigo-tools-api"
version = "1.0.1"
edition.workspace = true
description = "Protobuf API definitions for Fuigo tools"

[dependencies]
tonic-prost = { workspace = true }
# Protobuf runtime
prost = { workspace = true }
tonic = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
fuigo-tool-protocol = { workspace = true }

[build-dependencies]
fuigo-proto-build = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde", "tonic"]

[lints]
workspace = true
