//! Local speech detection over captured PCM.
//!
//! # Why this exists, and why it is not a transcript check
//!
//! The obvious way to answer "did the user say anything?" after a batch
//! transcription is to look at the returned text. That does not work. Probed
//! against the live FluxRouter endpoint with `flux-voice-fast`:
//!
//! ```text
//! silence.wav (6s of digital silence) -> {"text":" Thank you."}
//! noise.wav   (6s of white noise)     -> {"text":" ."}
//! ```
//!
//! Whisper-family models hallucinate stock phrases on silence. An empty-text
//! check would therefore have submitted **"Thank you."** to the coding agent as
//! if the user had spoken it.
//!
//! So the decision is made here, on the raw samples, *before* any request is
//! sent. That has a second benefit: when the user said nothing, a recording of
//! their room is never uploaded at all.
//!
//! # The test
//!
//! Per 30 ms frame, the frame mean is subtracted (see [`measure_frame`] on why
//! that matters), then two features are computed: RMS and zero-crossing rate.
//! A clip is speech when all of these hold:
//!
//! 1. At least [`MIN_ACTIVE_FRAMES`] frames clear [`RMS_FLOOR`]. A dead or
//!    permission-denied microphone returns digital silence -- the failure mode
//!    that actually happens on macOS -- and a single loud click is one frame,
//!    not an utterance.
//! 2. The loudest **active** frames cross zero at a rate that, read as a
//!    dominant frequency, is at least [`MIN_CROSSING_HZ`]. Mains hum and
//!    low-frequency rumble clear an energy gate easily; they cross zero far too
//!    rarely to be a voice.
//!
//! The frequency floor is expressed in Hz, not as a raw zero-crossing rate,
//! because the rate depends on the sample rate: the same voice measures 0.041
//! at 16 kHz and 0.014 at 48 kHz. `[voice].sample_rate` is user-configurable,
//! so a threshold fixed to a rate would silently reject real speech for anyone
//! who changed it. `rate * sample_rate / 2` recovers the dominant frequency and
//! holds at any rate -- checked against the fixtures, where it returns 60.1 Hz
//! for a 60 Hz hum and 434 Hz for a 440 Hz tone.
//!
//! # Two things this deliberately does NOT test, and why
//!
//! **An upper frequency bound.** There was one. Whispered and unvoiced speech
//! has no fundamental -- acoustically it *is* band-limited noise. The whisper
//! proxy in this module's tests measures 4243 Hz and the same noise with its
//! syllabic envelope removed measures 4253 Hz: 10 Hz apart, and `noise.wav`
//! (true white noise, not band-limited) sits at 4017 Hz among them. No ceiling
//! separates those, and the one that shipped first rejected every whisper,
//! silently discarding the dictation of anyone speaking quietly in a shared
//! room.
//!
//! **Amplitude modulation.** The obvious next idea, and it does not work. Speech
//! is syllabic and steady noise is not, so the variation of frame energy looks
//! like a clean discriminator -- until you notice that a push-to-talk recording
//! always begins and ends with the user not yet talking. That padding *is*
//! variation. Measured: a 440 Hz tone scores 0.004 unpadded and **0.348** with
//! 0.2 s of real room tone at each end, and steady white noise 0.022 and
//! **0.348** the same way. Every real recording is the padded case, so the
//! measure reports how much silence the clip has, not what the sound is. It
//! also cut the other way: a genuine half-second window of `speech.wav`
//! (t=1.86 s) scores 0.087, so any threshold high enough to reject the padded
//! tone also rejects real speech.
//!
//! Both were tried, both were wrong, and the note is here so they are not tried
//! again.
//!
//! Only *active* frames are ranked, and at most [`LOUDEST_ACTIVE_FRAMES`] of
//! them are read -- a fixed count, never a fraction of the clip. That is
//! load-bearing, and was got wrong first time round: averaging over the loudest
//! *decile of the whole clip* judges a short utterance mostly on the ambient
//! frames padding it out. Three seconds of speech in a 48-second toggle-mode
//! recording measured a decile-mean ZCR of 0.305 and was rejected; ranking
//! active frames only, capped at a fixed count, measures it at 0.039.
//!
//! # Measured evidence
//!
//! Every threshold below is set from these numbers, not from intuition, and
//! every number in the table was produced by running [`classify`] over the clip
//! named, at the constants this file now declares.
//!
//! `speech.wav`, `male.wav`, `male2.wav`, `fricative.wav` and `short.wav` are
//! synthesised speech (macOS `say`, resampled to the capture format).
//! `room.wav`, `quiet.wav` and `quiet_short.wav` are this machine's real
//! microphone, taken through the same `__mic-capture` helper the pager uses.
//! All are checked in under `tests/fixtures/`; the three tone rows are
//! generated by this module's own tests.
//!
//! | clip | peak frame RMS | active frames | crossing freq | verdict |
//! |---|---|---|---|---|
//! | `silence.wav` (digital silence) | 0.0000 | 0 of 200 | -- | reject |
//! | `room.wav` (real mic, quiet room) | **0.0023** | 0 of 189 | -- | reject |
//! | `quiet_short.wav` (real mic, quiet "yes") | 0.0081 | **6** of 75 | 643 Hz | accept |
//! | `quiet.wav` (real mic, quiet sentence) | **0.0087** | 44 of 174 | 546 Hz | accept |
//! | `noise.wav` (quiet white noise) | 0.00999 | 200 of 200 | 4017 Hz | **accept** |
//! | 85 Hz tone (a low male F0) | 0.1427 | 100 of 100 | **83.5 Hz** | reject |
//! | `short.wav` (the single word "yes") | 0.1554 | 14 of 14 | 2256 Hz | accept |
//! | `male.wav` | 0.2032 | 105 of 109 | 531 Hz | accept |
//! | 60 Hz mains hum @ 0.30 FS | 0.2209 | 100 of 100 | 60.1 Hz | reject |
//! | `male2.wav` | 0.2386 | 81 of 85 | 362 Hz | accept |
//! | `fricative.wav` ("she sells sea shells") | 0.2560 | 83 of 94 | 1105 Hz | accept |
//! | `speech.wav` (female) | 0.2737 | 105 of 109 | **326 Hz** | accept |
//! | 40 Hz rumble @ 0.50 FS | 0.3638 | 100 of 100 | 36.7 Hz | reject |
//!
//! The bolded cells are the pairs the two thresholds sit between: 0.0023 (room
//! tone) vs 0.0087 (the quietest real utterance) for energy, and 83.5 Hz vs
//! 326 Hz for frequency. `noise.wav` is bolded because it is the one row where
//! the energy floor was moved *through* a clip rather than around it: see
//! [`RMS_FLOOR`].
//!
//! The floor was 0.01 until these quiet captures were made, and at 0.01
//! `quiet.wav` produced **zero** active frames -- a whole spoken sentence
//! discarded without a request ever being sent. The same failure shows up in
//! the loud fixtures attenuated to a quiet capture's level: at 0.01,
//! `speech.wav` at 4% gain reached 5 active frames, `short.wav` at 10% reached
//! 4, and `male.wav` and `male2.wav` at 4% reached 0. Digital attenuation is
//! only a hint, though -- it scales a recording's own noise floor down with the
//! speech and so keeps an unrealistically clean SNR. `quiet.wav` and
//! `quiet_short.wav` are the real thing: a sentence and the single word "yes"
//! played across the room from the speakers and recorded, so the microphone and
//! room noise stayed put while the signal got small.
//!
//! # What this does NOT claim
//!
//! It is not a voice-activity detector and not a speaker check.
//!
//! It is an **emptiness** detector. It answers "was the microphone actually
//! carrying anything?", and it is deliberately biased toward saying yes.
//!
//! What it catches, all measured above: digital silence from a denied or muted
//! microphone (the failure that actually happens on macOS), a real microphone
//! in a real quiet room, mains hum, low-frequency rumble, and a lone click.
//!
//! What it does **not** catch, stated plainly rather than discovered later: a
//! steady broadband sound near the microphone -- a close fan, hiss, paper
//! rustling -- and a held mid-frequency tone. Both are inside the region real
//! speech occupies on every measure tried, and the two candidate tests that
//! would have excluded them (a frequency ceiling, an amplitude-modulation
//! floor) each rejected real speech instead; see above.
//!
//! Broadband noise used to escape on energy alone as long as it was quiet
//! enough, and no longer does: `noise.wav` peaks at 0.00999, which cleared the
//! old 0.01 floor by nothing at all and clears the one [`RMS_FLOOR`] now sets
//! by 2.0x, so it is accepted. That is a deliberate trade, not an oversight --
//! the floor that rejected it also rejected `quiet.wav` outright -- and it is
//! pinned by a test so it stays a decision.
//!
//! That asymmetry is the design, and the two failures are not equal. A false
//! negative is the silent one: the dictation the user has already spoken is
//! discarded, no request is sent, and nothing on screen says why -- they simply
//! have to say it again. A false positive is visible: it costs one request
//! whose hallucinated stock phrase lands in the prompt box, where the user can
//! read it and delete it before sending. Given the choice, this gate errs
//! toward the visible failure. That is the whole reason [`RMS_FLOOR`] now sits
//! below `noise.wav` and accepts it.

/// Frame length for the analysis window, in milliseconds.
///
/// 30 ms is the usual speech-analysis frame: long enough for a stable RMS and
/// several pitch periods, short enough that a single word is many frames.
const FRAME_MS: u32 = 30;

/// Most frames the zero-crossing test reads, taken from the loudest active
/// frames.
///
/// A fixed count (~1.5 s of audio) rather than a fraction of the clip, so the
/// verdict does not depend on how long the microphone was open around what the
/// user actually said.
const LOUDEST_ACTIVE_FRAMES: usize = 50;

/// Minimum frames clearing [`RMS_FLOOR`] before a clip can be speech.
///
/// Four frames is 120 ms. This is where the short-utterance safety lives,
/// because [`RMS_FLOOR`] cannot carry it: `quiet_short.wav`, a real quiet
/// recording of the single word "yes", clears the floor in exactly **6**
/// frames. A minimum of 6 -- what this was -- would accept that clip with no
/// margin whatsoever and destroy anything a shade quieter or shorter. At 4 it
/// has 1.5x. The louder `short.wav` has 14 active frames, 3.5x.
///
/// The other side is measured too, at the floor as it now stands. Three clicks
/// played into this machine's microphone produced **1** active frame between
/// them, and the synthetic 12.5 ms transient in this module's tests produces 1
/// as well, so a lone click stays 4x under the minimum.
pub const MIN_ACTIVE_FRAMES: usize = 4;

/// Minimum frame RMS, as a fraction of full scale, for a frame to count as
/// carrying signal.
///
/// The pair this sits between is a real one, measured on the same microphone
/// through the same capture helper, not one recording scaled down to imitate
/// the other. `room.wav` -- an empty room -- peaks at **0.0023**, and
/// `quiet.wav` -- a sentence played across that room and recorded -- peaks at
/// **0.0087**. 0.005 is 2.2x above the room and 1.7x below the utterance.
/// `quiet_short.wav`, the quietest accepted clip, peaks at 0.0081, 1.6x above.
/// Re-recording the same room while setting this floor gave 0.0028 over 2 s, so
/// `room.wav` is not a lucky sample; the loudest room frame measured either way
/// stays under 0.005, and neither clip produces a single active frame.
///
/// This was 0.01, which is above `quiet.wav` entirely: that clip yielded zero
/// active frames and the whole sentence was thrown away. That is the failure
/// this constant exists to avoid, so it is set below the quiet capture, not
/// above it.
///
/// The move has one price and it is paid knowingly: `noise.wav`, six seconds of
/// quiet white noise, peaks at 0.00999 -- it used to be rejected only because
/// that is a hair under 0.01 -- and now clears the floor in every one of its
/// 200 frames, so it is accepted and costs one wasted request. It is
/// asserted as accepted in `tests/speech_gate_fixtures.rs` so the trade is
/// recorded rather than rediscovered. The reasoning is at the end of the module
/// docs: a false positive is visible in the prompt box, a false negative is
/// not visible anywhere.
///
/// It is an emptiness test and nothing more. A previous version of this comment
/// claimed it "rejects 60 Hz hum on energy alone", which is false: hum at any
/// audible level clears this floor easily -- the table above records 0.2209 for
/// it. Hum is rejected by [`MIN_CROSSING_HZ`], not here.
pub const RMS_FLOOR: f32 = 0.005;

/// Lowest crossing frequency, in Hz, that can still be speech.
///
/// An 85 Hz tone -- about as low as a male speaking fundamental goes -- lands
/// at 83.5 Hz, and the least noisy real speech (`speech.wav`) at 326 Hz. 160
/// sits between them, 1.9x over the tone and 2.0x under the speech. The quiet
/// captures are not the tight case here: `quiet.wav` measures 546 Hz and
/// `quiet_short.wav` 643 Hz. Below this floor the signal has energy but almost
/// no spectral content: a hum or a rumble, not a voice.
pub const MIN_CROSSING_HZ: f32 = 160.0;

/// Why [`classify`] reached its verdict. Carried so a caller can log or test
/// the measurement rather than only the boolean.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SpeechAnalysis {
    /// Loudest frame's RMS, as a fraction of full scale, after DC removal.
    pub peak_frame_rms: f32,
    /// Dominant frequency of the loudest active frames, in Hz, estimated from
    /// their zero-crossing rate. Zero when there are no active frames.
    ///
    /// Held in Hz rather than as a raw rate so [`SpeechAnalysis::is_speech`] is
    /// independent of the sample rate the clip was captured at.
    pub loud_frame_crossing_hz: f32,
    /// Frames clearing [`RMS_FLOOR`].
    pub active_frames: usize,
    /// Whole frames analysed. Zero for a clip shorter than one frame.
    pub frames: usize,
}

impl SpeechAnalysis {
    /// Whether this measurement clears every gate.
    pub fn is_speech(&self) -> bool {
        self.active_frames >= MIN_ACTIVE_FRAMES && self.loud_frame_crossing_hz >= MIN_CROSSING_HZ
    }
}

/// Whether `pcm` plausibly contains speech.
///
/// `pcm` is little-endian 16-bit mono, the format the capture backends produce
/// and the only format [`crate::stt::batch::pcm_to_wav`] declares.
pub fn contains_speech(pcm: &[u8], sample_rate: u32) -> bool {
    classify(pcm, sample_rate).is_speech()
}

/// [`contains_speech`] with the measurements it was based on.
pub fn classify(pcm: &[u8], sample_rate: u32) -> SpeechAnalysis {
    let frame_len = frame_len_samples(sample_rate);
    // A clip shorter than one frame is not evidence of speech. Treating a stray
    // 10 ms of PCM as an utterance would upload a fragment and let the endpoint
    // hallucinate a sentence over it.
    let samples = pcm.len() / 2;
    if frame_len == 0 || samples < frame_len {
        return SpeechAnalysis {
            peak_frame_rms: 0.0,
            loud_frame_crossing_hz: 0.0,
            active_frames: 0,
            frames: 0,
        };
    }

    let frame_count = samples / frame_len;
    let mut peak_frame_rms = 0.0f32;
    // (rms, zcr) for frames carrying signal. A trailing partial frame is
    // dropped: its RMS is computed over fewer samples and is not comparable.
    let mut active: Vec<(f32, f32)> = Vec::new();
    for frame in 0..frame_count {
        let (rms, zcr) = measure_frame(pcm, frame * frame_len, frame_len);
        peak_frame_rms = peak_frame_rms.max(rms);
        if rms >= RMS_FLOOR {
            active.push((rms, zcr));
        }
    }

    // Rank active frames by energy and read the zero-crossing rate of the
    // loudest slice. `total_cmp` keeps this NaN-safe; RMS cannot be NaN here,
    // but the compare must still be total.
    active.sort_by(|a, b| b.0.total_cmp(&a.0));
    let read = active.len().min(LOUDEST_ACTIVE_FRAMES);
    #[allow(clippy::cast_precision_loss)] // `read` is at most 50
    let mean_zcr = if read == 0 {
        0.0
    } else {
        active[..read].iter().map(|(_, zcr)| *zcr).sum::<f32>() / read as f32
    };
    // A signal crossing zero `r` times per sample completes `r / 2` cycles per
    // sample, so its dominant frequency is `r * rate / 2`. Verified against the
    // fixtures: a 60 Hz hum reads 60.1 Hz and a 440 Hz tone 434 Hz.
    #[allow(clippy::cast_precision_loss)] // sample rates are small integers
    let loud_frame_crossing_hz = mean_zcr * sample_rate as f32 / 2.0;

    SpeechAnalysis {
        peak_frame_rms,
        loud_frame_crossing_hz,
        active_frames: active.len(),
        frames: frame_count,
    }
}

/// One frame's RMS (as a fraction of full scale) and zero-crossing rate, both
/// measured about the frame's own mean.
///
/// Removing the mean is not cosmetic. The zero-crossing test asks how often the
/// waveform changes sign, and a constant offset moves the axis it is measured
/// against: white noise with a 2% DC offset crosses the *zero* line almost
/// never, so an offset alone drops its measured rate from 0.51 to 0.0004 and
/// walks it straight through a naive gate. Subtracting the mean measures sign
/// changes about the signal, which is what the test is actually asking. It also
/// stops a DC offset from inflating RMS and faking signal where there is none.
fn measure_frame(pcm: &[u8], start: usize, frame_len: usize) -> (f32, f32) {
    let mut sum = 0.0f64;
    for offset in 0..frame_len {
        sum += f64::from(sample_at(pcm, start + offset));
    }
    #[allow(clippy::cast_precision_loss)] // frame_len is 480 at 16 kHz
    let n = frame_len as f64;
    let mean = sum / n;

    let mut sum_squares = 0.0f64;
    let mut crossings = 0usize;
    let mut prev_negative = f64::from(sample_at(pcm, start)) - mean < 0.0;
    for offset in 0..frame_len {
        let centred = f64::from(sample_at(pcm, start + offset)) - mean;
        sum_squares += centred * centred;
        let negative = centred < 0.0;
        if offset > 0 && negative != prev_negative {
            crossings += 1;
        }
        prev_negative = negative;
    }
    let rms = (sum_squares / n).sqrt() / f64::from(i16::MAX);
    #[allow(clippy::cast_precision_loss)]
    let zcr = crossings as f64 / (n - 1.0);
    #[allow(clippy::cast_possible_truncation)]
    (rms as f32, zcr as f32)
}

/// Samples in one [`FRAME_MS`] frame at `sample_rate`.
fn frame_len_samples(sample_rate: u32) -> usize {
    (sample_rate as usize) * (FRAME_MS as usize) / 1000
}

/// The `index`-th little-endian i16 sample. The caller has already bounded
/// `index` by `pcm.len() / 2`.
fn sample_at(pcm: &[u8], index: usize) -> i16 {
    i16::from_le_bytes([pcm[index * 2], pcm[index * 2 + 1]])
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::TAU;

    /// Build `secs` of little-endian 16-bit mono PCM from a sample function
    /// over time in seconds.
    fn pcm(sample_rate: u32, secs: f32, mut f: impl FnMut(f32) -> f32) -> Vec<u8> {
        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let n = (sample_rate as f32 * secs) as usize;
        let mut out = Vec::with_capacity(n * 2);
        for i in 0..n {
            #[allow(clippy::cast_precision_loss)]
            let t = i as f32 / sample_rate as f32;
            #[allow(clippy::cast_possible_truncation)]
            let s = (f(t).clamp(-1.0, 1.0) * f32::from(i16::MAX)) as i16;
            out.extend_from_slice(&s.to_le_bytes());
        }
        out
    }

    /// A deterministic LCG, so noise tests never flake on a seed.
    fn noise(amplitude: f32, secs: f32, offset: f32) -> Vec<u8> {
        let mut state = 0x2545_F491_4F6C_DD1Du64;
        pcm(16_000, secs, move |_| {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1);
            #[allow(clippy::cast_precision_loss)]
            let unit = (state >> 33) as f32 / (1u64 << 31) as f32;
            (unit * 2.0 - 1.0) * amplitude + offset
        })
    }

    /// Band-limited noise (roughly 1-6 kHz), optionally with a syllable-rate
    /// envelope. Unvoiced speech and steady hiss differ by little else.
    fn modulated_noise(amplitude: f32, secs: f32, modulated: bool) -> Vec<u8> {
        use std::f32::consts::TAU;
        let mut state = 0x9E37_79B9_7F4A_7C15u64;
        let (mut low, mut high) = (0.0f32, 0.0f32);
        let a_high = (-TAU * 6000.0 / 16_000.0).exp();
        let a_low = (-TAU * 1000.0 / 16_000.0).exp();
        pcm(16_000, secs, move |t| {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1);
            #[allow(clippy::cast_precision_loss)]
            let white = (state >> 33) as f32 / (1u64 << 31) as f32 * 2.0 - 1.0;
            high = (1.0 - a_high) * white + a_high * high;
            low = (1.0 - a_low) * white + a_low * low;
            let envelope = if modulated {
                0.55 + 0.45 * (TAU * 3.5 * t).sin()
            } else {
                1.0
            };
            (high - low) * envelope * amplitude * 3.0
        })
    }

    #[test]
    fn digital_silence_is_not_speech() {
        let analysis = classify(&vec![0u8; 16_000 * 2], 16_000);
        assert_eq!(analysis.peak_frame_rms, 0.0);
        assert_eq!(analysis.active_frames, 0);
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// Whispered and unvoiced speech is acoustically band-limited noise: it
    /// measures within 10 Hz of steady hiss. This gate accepts both, and that is
    /// the documented trade -- accepting a whisper is worth accepting hiss,
    /// because rejecting a whisper destroys dictation silently.
    ///
    /// The assertion that matters is the first one. The second records the
    /// limitation so it is a decision, not an accident.
    #[test]
    fn a_whisper_is_accepted_and_so_is_the_hiss_it_cannot_be_told_from() {
        let whisper = classify(&modulated_noise(0.25, 2.0, true), 16_000);
        let hiss = classify(&modulated_noise(0.25, 2.0, false), 16_000);
        assert!(
            whisper.is_speech(),
            "a whisper must not be discarded: {whisper:?}"
        );
        assert!(
            hiss.is_speech(),
            "documented limitation; if this ever changes, update the module docs: {hiss:?}"
        );
        assert!(
            (whisper.loud_frame_crossing_hz - hiss.loud_frame_crossing_hz).abs() < 100.0,
            "these are the same kind of signal, which is the whole point: \
             whisper={whisper:?} hiss={hiss:?}"
        );
    }

    /// A DC offset moves the axis the sign test measures against. Without the
    /// per-frame mean removal in `measure_frame`, this noise measures a
    /// crossing frequency near 3 Hz and would be judged on a number describing
    /// the offset rather than the signal.
    #[test]
    fn a_dc_offset_does_not_distort_the_measurement() {
        let clean = classify(&noise(0.3, 1.0, 0.0), 16_000);
        let offset = classify(&noise(0.3, 1.0, 0.2), 16_000);
        assert!(
            (clean.loud_frame_crossing_hz - offset.loud_frame_crossing_hz).abs()
                < clean.loud_frame_crossing_hz * 0.1,
            "DC removal must keep the measurement on the signal: clean={clean:?} offset={offset:?}"
        );
        // Both are accepted -- loud broadband noise is the documented
        // limitation -- so the verdict proves nothing here. What matters is that
        // an offset does not change what is measured.
        assert_eq!(
            clean.is_speech(),
            offset.is_speech(),
            "an offset must not change the verdict: clean={clean:?} offset={offset:?}"
        );
    }

    /// Mains hum clears any energy gate but crosses zero far too rarely to be a
    /// voice. This is the case `MIN_CROSSING_HZ` exists for.
    #[test]
    fn loud_mains_hum_is_rejected_on_the_zero_crossing_floor() {
        let analysis = classify(&pcm(16_000, 3.0, |t| 0.30 * (TAU * 60.0 * t).sin()), 16_000);
        assert!(
            analysis.peak_frame_rms > RMS_FLOOR,
            "hum must be loud enough that only the ZCR floor rejects it: {analysis:?}"
        );
        assert!(
            analysis.loud_frame_crossing_hz < MIN_CROSSING_HZ,
            "{analysis:?}"
        );
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    #[test]
    fn low_frequency_rumble_is_rejected() {
        let analysis = classify(&pcm(16_000, 3.0, |t| 0.50 * (TAU * 40.0 * t).sin()), 16_000);
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// 85 Hz is about as low as a male speaking fundamental goes, and a pure
    /// tone there is still rejected -- the floor sits below real speech, not
    /// below every possible pitch.
    #[test]
    fn a_tone_at_a_low_male_fundamental_is_still_rejected() {
        let analysis = classify(&pcm(16_000, 3.0, |t| 0.20 * (TAU * 85.0 * t).sin()), 16_000);
        assert!(
            analysis.loud_frame_crossing_hz < MIN_CROSSING_HZ,
            "{analysis:?}"
        );
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// A held mid-frequency tone sits exactly where real speech sits, so this
    /// gate accepts it. Recorded as a decision, not left to be discovered.
    #[test]
    fn a_sustained_mid_frequency_tone_is_accepted_and_that_is_a_known_limit() {
        let analysis = classify(
            &pcm(16_000, 3.0, |t| 0.20 * (TAU * 440.0 * t).sin()),
            16_000,
        );
        assert!(
            analysis.loud_frame_crossing_hz > MIN_CROSSING_HZ,
            "a 440 Hz tone is inside the range real voices occupy: {analysis:?}"
        );
        assert!(
            analysis.is_speech(),
            "documented limitation; if this ever changes, update the module docs: {analysis:?}"
        );
    }

    /// The band is in Hz precisely so it holds at any capture rate.
    /// `[voice].sample_rate` is user-configurable, and a threshold fixed to a
    /// zero-crossing *rate* would reject the same voice at 48 kHz that it
    /// accepts at 16 kHz -- the rate scales inversely with the sample rate.
    #[test]
    fn the_verdict_does_not_depend_on_the_sample_rate() {
        for rate in [8_000u32, 16_000, 24_000, 44_100, 48_000] {
            let voiced = pcm(rate, 1.0, |t| {
                let envelope = 0.5 + 0.5 * (TAU * 4.0 * t).sin();
                let harmonics = (TAU * 220.0 * t).sin() * 0.6
                    + (TAU * 440.0 * t).sin() * 0.3
                    + (TAU * 660.0 * t).sin() * 0.1;
                envelope * harmonics * 0.8
            });
            let analysis = classify(&voiced, rate);
            assert!(
                analysis.is_speech(),
                "the same waveform must pass at {rate} Hz: {analysis:?}"
            );
            // And the measurement must land on the signal's actual content,
            // not on an artefact of the rate.
            assert!(
                (analysis.loud_frame_crossing_hz - 220.0).abs() < 120.0,
                "crossing frequency at {rate} Hz should track the fundamental: {analysis:?}"
            );
        }
    }

    /// The converse: a hum stays rejected at every rate too.
    #[test]
    fn a_hum_is_rejected_at_every_sample_rate() {
        for rate in [8_000u32, 16_000, 48_000] {
            let hum = pcm(rate, 3.0, |t| 0.30 * (TAU * 60.0 * t).sin());
            let analysis = classify(&hum, rate);
            assert!(!analysis.is_speech(), "hum at {rate} Hz: {analysis:?}");
        }
    }

    /// A single click is one frame of signal, not an utterance.
    ///
    /// This pins the number [`MIN_ACTIVE_FRAMES`] is documented against. A
    /// 12.5 ms full-scale transient occupies exactly one frame, so the minimum
    /// of 4 has 4x over it. Three clicks played acoustically into this
    /// machine's microphone measured 1 active frame between them, so the
    /// synthetic case is not flattering the real one.
    #[test]
    fn a_lone_transient_is_not_an_utterance() {
        let mut clip = vec![0u8; 16_000 * 2];
        for i in 0..200 {
            clip[i * 2..i * 2 + 2].copy_from_slice(&i16::MAX.to_le_bytes());
        }
        let analysis = classify(&clip, 16_000);
        assert_eq!(
            analysis.active_frames, 1,
            "a click is one frame, and MIN_ACTIVE_FRAMES is documented against \
             that: {analysis:?}"
        );
        assert!(
            analysis.active_frames < MIN_ACTIVE_FRAMES,
            "a click must not reach the frame minimum: {analysis:?}"
        );
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// Very quiet audio -- a muted or distant mic -- fails the energy gate even
    /// though its zero-crossing rate looks speech-like.
    #[test]
    fn near_silent_tone_fails_the_energy_gate() {
        let analysis = classify(
            &pcm(16_000, 1.0, |t| 0.0005 * (TAU * 200.0 * t).sin()),
            16_000,
        );
        assert_eq!(analysis.active_frames, 0, "{analysis:?}");
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// Less than one frame of audio is not an utterance, whatever it contains.
    #[test]
    fn a_fragment_shorter_than_one_frame_is_not_speech() {
        let one_frame = frame_len_samples(16_000);
        let analysis = classify(&vec![0x7fu8; (one_frame - 1) * 2], 16_000);
        assert_eq!(analysis.frames, 0);
        assert!(!analysis.is_speech(), "{analysis:?}");
    }

    /// An odd trailing byte must not panic or read out of bounds.
    #[test]
    fn odd_length_pcm_is_handled() {
        let mut odd = vec![0u8; 16_000 * 2];
        odd.push(0x01);
        let _ = classify(&odd, 16_000);
    }

    #[test]
    fn zero_sample_rate_does_not_divide_by_zero() {
        let analysis = classify(&vec![0u8; 1024], 0);
        assert_eq!(analysis.frames, 0);
        assert!(!analysis.is_speech());
    }
}
